### ISSUE TITLE
Add `File System Access API` with non-OPFS

### ISSUE THREAD

**Issue by marto55555** [shalanah/ios404#11]
Safari supports the `File System Access API`, but with origin private file system only. This limits users and that they cannot pick a file/folder location of their choice, and they cannot view the files through a file manager. This missing feature can be detected by the lack of picker methods, such as:

- https://caniuse.com/mdn-api_window_showdirectorypicker
- https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker

**Comment by shalanah** [comment]
@marto55555 Another good find :) 

Will be covered in #13
