### ISSUE TITLE
Add `Web Share Target API`

### ISSUE THREAD

**Issue by marto55555** [shalanah/ios404#12]
On iOS, installed PWAs cannot receive shared text and files from other apps: https://caniuse.com/mdn-html_manifest_share_target

**Comment by shalanah** [comment]
Hi @marto55555 ! Good point.

Caniuse has it's own dataset but also pulls in MDN data. You can see it in the url of the link starting with `mdn-`. I didn't know this at first about caniuse either. 

I just added the issue #13 because the features you're flagging.
