### ISSUE TITLE
iOS Safari does not correctly implement `scroll-padding`

### ISSUE THREAD

**Issue by jeffijoe** [shalanah/ios404#17]
I found your site in frustration over mobile Safari, great work!

One of the missing features of mobile Safari which doesn't seem to be listed is `scroll-padding`. iOS Safari does not respect scroll-padding in all scrollable containers. [This SO answer from 2019](https://stackoverflow.com/a/58890319/561545) noted that a ticket has been filed. The linked bug ticket has been marked as resolved, but [the related meta-ticket](https://bugs.webkit.org/show_bug.cgi?id=218115) is still open.

Is this worth adding?

**Comment by shalanah** [comment]
Hi @jeffijoe! Thanks and welcome!

Would that be included in https://ios404.com/#css-scrollbar ?
Here's the caniuse data link: https://caniuse.com/css-scrollbar

Right now I'm using caniuse data directly as my source. 
That would be your first place to add missing features and ios404 should update accordingly. 

Caniuse also pulls in MDN data here and there as a separate source which I haven't integrated yet. 

I'm still hoping to do so!

**Comment by jeffijoe** [comment]
I guess I'm not entirely sure whether `caniuse` treats "supposedly implemented but doesn't actually work" as "supported" 😅

**Comment by shalanah** [comment]
Hmmm interesting.

This search on caniuse pulls up only MDN data (different than caniuse data) https://caniuse.com/?search=scroll-padding

You can tell by the bottom of the feature it says "Support data for this feature provided by: MDN browser-compat-data" which is a bit hidden.

Looks like MDN could use some updating then?

**Comment by shalanah** [comment]
@jeffijoe I'm going to close this issue for now. I'm noting It is related to #13 

I hope you file a issue with MDN browser-compat-data. It's always good to have accurate support data!
