### ISSUE TITLE
Add `prefers-reduced-transparency` CSS media query as missing from Safari

### ISSUE THREAD

**Issue by coliff** [shalanah/ios404#5]
REF: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-transparency

I'd like this to be added to Safari!

**Comment by shalanah** [comment]
Cool! This media query is new to me thanks for pointing out!

We have 2 options here. 
- 1. Create new issue: Ask for MDN support on iOS404
- 2. You can ask caniuse to add this to their tracking (current source for feature data)

**Comment by coliff** [comment]
Thanks! I made an issue on the CanIuse tracker.
https://github.com/Fyrd/caniuse/issues/7017

**Comment by shalanah** [comment]
Awesome!

Feel free to open another issue if you'd like MDN support in the future. 

If the feature lands in caniuse and there is a discrepancy between iOS and a comparison browsers it will automatically show up on iOS404 (It fetches the latest caniuse).

**Comment by shalanah** [comment]
Adding this is related to #13
